name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # allows manual run

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      pgsql:
        image: postgres:15
        env:
          POSTGRES_DB: raafco_ims_pgsql
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d raafco_ims_pgsql"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_pgsql, redis, bcmath, pcntl, zip
          coverage: none

      - name: Install Composer dependencies
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Copy .env.testing
        working-directory: ./src
        run: cp .env.testing .env

      - name: Generate app key
        working-directory: ./src
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./src
        run: php artisan migrate --force

      - name: Run Pint (code style)
        working-directory: ./src
        run: ./vendor/bin/pint --test

      - name: Run PHPStan (static analysis)
        working-directory: ./src
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      - name: Run Pest tests
        working-directory: ./src
        run: ./vendor/bin/pest
