name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      pgsql:
        image: postgres:15
        env:
          POSTGRES_DB: raafco_ims_pgsql
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd "pg_isready -U admin"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: pgsql, pdo_pgsql, bcmath, mbstring, tokenizer, intl, pcntl, zip
          coverage: none

      - name: Install Composer dependencies
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env.testing
        working-directory: ./src
        run: cp .env.testing .env

      - name: Generate app key
        working-directory: ./src
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./src
        run: php artisan migrate --force

      - name: Run Pint (code style)
        working-directory: ./src
        run: ./vendor/bin/pint --test

      - name: Run PHPStan (static analysis)
        working-directory: ./src
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      - name: Run tests
        working-directory: ./src
        run: php artisan test
