name: Psalm Static Analysis

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  psalm-analysis:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.3"]

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: mbstring, pdo_pgsql

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('src/composer.lock') }}
          restore-keys: composer-

      - name: Cache Psalm analysis
        uses: actions/cache@v4
        with:
          path: /tmp/psalm
          key: psalm-${{ github.sha }}
          restore-keys: psalm-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Psalm
        working-directory: src
        run: ./vendor/bin/psalm --shepherd --stats --output-format=github
